
export const headers = {
    "SL_NO": "Sl No",
    "SoO_NO": "SoO No",
    "AD Code": "AD Code",
    "Exp Serial": "EXP Serial",
    "EXP Year": "EXP Year",
    "COUNTRY OF DESTINATION": "Country Of Destination",
    "Select Importer": "Select Importer",
    "No. & Kind of Packages": "No. & Kind of Packages",
    "HS Codes": "HS Codes",
    "Quantities": "Quantities",
    "Loading Port and Route": "Loading Port and Route",
    "Bill of Lading (B/L) No": "Bill of Lading (B/L) No",
    "Bill of Lading (B/L) Date": "Bill of Lading (B/L) Date",
    "Vessel": "Vessel",
    "Container": "Container",
    "Item No.": "Item No",
    "Marks & No. of Packages": "Marks & No. of Packages",
    "EXP Date": "EXP Date",
    "LC No./Sales Contract": "LC No./Sales Contract",
    "LC/SC Date": "LC/SC Date",
    "UD No.": "UD No",
    "UD Date": "UD Date",
    "Bill of Export (Shipping Bill) No.": "Bill of Export (Shipping Bill) No",
    "Bill of Export Date": "Bill of Export Date",
    "Origin": "Origin",
    "Unit Types": "Unit Types",
    "Invoice No.": "Invoice No",
    "Invoice Date": "Invoice Date",
    "Currency": "Currency",
    "Invoice Value": "Invoice Value",
    "Status": "Status",
    "Comment": "Comment",
    "Error Column": "Error Column",
}

export const fullHeaders = Object.values(headers);
export const headerKeys = Object.keys(headers);